# Generated by Django 4.2 on 2023-04-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='session_id',
            field=models.CharField(default=-1234567890, max_length=36),
            preserve_default=False,
        ),
    ]
