# Generated by Django 4.2 on 2023-04-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_player_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemetry',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
