# Generated by Django 4.2 on 2023-04-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_rename_timestamp_telemetry_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='session_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
